seata:
  enabled: true
  # 事务群组（可以每个应用独立取名，也可以使用相同的名字）
  tx-service-group: seata_group
  client:
    rm-report-success-enable: true
    # 自动刷新缓存中的表结构（默认false）
    rm-table-meta-check-enable: false
    # 一阶段结果上报TC重试次数（默认5）
    rm-report-retry-count: 5
    # 异步提交缓存队列长度（默认10000）
    rm-async-commit-buffer-limit: 10000
    rm:
      lock:
        # 校验或占用全局锁重试间隔（默认10ms）
        lock-retry-internal: 10
        # 校验或占用全局锁重试次数（默认30）
        lock-retry-times: 30
        # 分支事务与其它全局回滚事务冲突时锁策略（优先释放本地锁让回滚成功）
        lock-retry-policy-branch-rollback-on-conflict: true
        # 一阶段全局提交结果上报TC重试次数（默认1次，建议大于1）
    tm-commit-retry-count: 3
    # 一阶段全局回滚结果上报TC重试次数（默认1次，建议大于1）
    tm-rollback-retry-count: 3
    undo:
      # 二阶段回滚镜像校验（默认true开启）
      data-validation: true
      # undo序列化方式（默认jackson 不支持 LocalDateTime）
      log-serialization: jackson
      # 自定义undo表名（默认undo_log）
      log-table: undo_log
    log:
      # 日志异常输出概率（默认100）
      exceptionRate: 100
    support:
      spring:
        datasource-autoproxy: true
  service:
    vgroup-mapping:
      # TC 集群（必须与seata-server保持一致）
      pig_tx_group: default
      # 降级开关
    enable-degrade: false
    # 禁用全局事务（默认false）
    disable-global-transaction: false
    grouplist:
      default: seata:8091
  transport:
    shutdown:
      wait: 3
    thread-factory:
      boss-thread-prefix: NettyBoss
      worker-thread-prefix: NettyServerNIOWorker
      server-executor-thread-prefix: NettyServerBizHandler
      share-boss-worker: false
      client-selector-thread-prefix: NettyClientSelector
      client-selector-thread-size: 1
      client-worker-thread-prefix: NettyClientWorkerThread
    type: TCP
    server: NIO
    heartbeat: true
    serialization: seata
    compressor: none
    # 客户端事务消息请求是否批量合并发送（默认true）
    enable-client-batch-send-request: true
  registry:
    file:
      name: file.conf
    type: file
  config:
    file:
      name: file.conf
    type: file
